source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IOStickyHeader_Example' do
  pod "IOStickyHeader", :path => "../"
end

target 'IOStickyHeader_Tests' do
  pod "IOStickyHeader", :path => "../"


end
