source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IOStickyHeader_Example', :exclusive => true do
  pod "IOStickyHeader", :path => "../"
end

target 'IOStickyHeader_Tests', :exclusive => true do
  pod "IOStickyHeader", :path => "../"

  
end
